name: Package dotnet tool
on:    
  push:
    branches:    
      - master
    paths:
      - 'src/tool/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:3.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package project
        run: dotnet pack src/tool/CosmicWorks.Tool.csproj --output out --configuration release -p:Version=0.1.${{ github.run_number }}-preview
      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v2
        with:
          name: NuGet packages
          path: out